#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBox;
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}

namespace TestWFP
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ Algo;
        private: ::Windows::UI::Xaml::Controls::Grid^ show;
        private: ::Windows::UI::Xaml::Controls::Grid^ Function;
        private: ::Windows::UI::Xaml::Controls::Grid^ add;
        private: ::Windows::UI::Xaml::Controls::TextBox^ sys_Time;
        private: ::Windows::UI::Xaml::Controls::Button^ step;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ show_msg;
    };
}

